"""criação inicial

Revision ID: 487bfc9e42c8
Revises: 
Create Date: 2025-08-08 02:27:02.483877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487bfc9e42c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fator_divisao', sa.Float(), nullable=False),
    sa.Column('porcentagem_frete', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('unidade_medida', sa.String(length=10), nullable=True),
    sa.Column('valor_frete', sa.Float(), nullable=True),
    sa.Column('codigo_gerado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('numero_orcamento', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_orcamento', sa.DateTime(), nullable=True),
    sa.Column('descricao_servico', sa.Text(), nullable=False),
    sa.Column('valor_mao_obra', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_orcamento')
    )
    op.create_table('item_orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('total_item', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('numero_ordem', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_ordem'),
    sa.UniqueConstraint('orcamento_id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('termos_condicoes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_contrato'),
    sa.UniqueConstraint('ordem_servico_id')
    )
    op.create_table('item_ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('total_item', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('numero_nf', sa.String(length=50), nullable=False),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_nf'),
    sa.UniqueConstraint('ordem_servico_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_fiscal')
    op.drop_table('item_ordem_servico')
    op.drop_table('contrato')
    op.drop_table('ordem_servico')
    op.drop_table('item_orcamento')
    op.drop_table('orcamento')
    op.drop_table('usuarios')
    op.drop_table('material')
    op.drop_table('configuracoes')
    op.drop_table('cliente')
    # ### end Alembic commands ###
